version: '2'
services:
  testrunner:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    volumes:
      - ./:/usr/src/app/


  pip-installer:
    build: ./
    entrypoint: /usr/src/app/pip-installer.sh