version: '2'
services:
  web:
    links:
      - postgres:postgres
    env_file: .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres

#  web-manage.local:
#    links:
#      - postgres:postgres
#    environment:
#      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
#
  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
