"""empty message

Revision ID: 158f5b7bcaff
Revises: 553b3a36d3fa
Create Date: 2016-07-06 17:45:03.413821

"""

# revision identifiers, used by Alembic.
revision = '158f5b7bcaff'
down_revision = '553b3a36d3fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiware_poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi_uuid', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('video_poi', 'user_poi', name='poi_category'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poi_uuid')
    )
    op.create_table('pois_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poi_id'], ['fiware_poi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('pois_videos',
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('poi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poi_id'], ['fiware_poi.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pois_videos')
    op.drop_table('pois_users')
    op.drop_table('fiware_poi')
    ### end Alembic commands ###
