"""empty message

Revision ID: 64a815e00b4e
Revises: 158f5b7bcaff
Create Date: 2016-07-08 15:02:30.139989

"""

# revision identifiers, used by Alembic.
revision = '64a815e00b4e'
down_revision = '158f5b7bcaff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('campaign', sa.String(length=50), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_code'), 'promo_code', ['code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code_code'), table_name='promo_code')
    op.drop_table('promo_code')
    ### end Alembic commands ###
