"""empty message

Revision ID: ce712f69ccba
Revises: 64a815e00b4e
Create Date: 2016-07-12 10:26:04.781384

"""

# revision identifiers, used by Alembic.
revision = 'ce712f69ccba'
down_revision = '64a815e00b4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_code', sa.Column('redeemed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_code', 'redeemed_at')
    ### end Alembic commands ###
